<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ReachForge.Web\ReachForge.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\ReachForge.Application.Tests\PostgresTestDatabase.cs" Link="PostgresTestDatabase.cs" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="ReachForge.Tests" />
  </ItemGroup>
</Project>
